# Generated by Django 2.2.5 on 2019-09-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essencias_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'verbose_name_plural': 'Coleções'},
        ),
    ]
