# Generated by Django 2.2.5 on 2020-01-15 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essencias_catalogo', '0004_auto_20200114_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
