# Generated by Django 2.2.5 on 2020-01-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essencias_catalogo', '0005_collection_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name_pt',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
